# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"o\n\x0bVectorClock\x12\x32\n\x05\x63lock\x18\x01 \x03(\x0b\x32#.suggestions.VectorClock.ClockEntry\x1a,\n\nClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"~\n\x10InitOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x17\n\x0fpurchased_items\x18\x03 \x03(\t\x12.\n\x0cvector_clock\x18\x04 \x01(\x0b\x32\x18.suggestions.VectorClock\"e\n\x11InitOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12.\n\x0cvector_clock\x18\x03 \x01(\x0b\x32\x18.suggestions.VectorClock\"P\n\x0c\x45ventRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12.\n\x0cvector_clock\x18\x02 \x01(\x0b\x32\x18.suggestions.VectorClock\"[\n\x11\x43learOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x34\n\x12\x66inal_vector_clock\x18\x02 \x01(\x0b\x32\x18.suggestions.VectorClock\"f\n\x12\x43learOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12.\n\x0cvector_clock\x18\x03 \x01(\x0b\x32\x18.suggestions.VectorClock\"6\n\x04\x42ook\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"\x8e\x01\n\x13SuggestionsResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12*\n\x0fsuggested_books\x18\x03 \x03(\x0b\x32\x11.suggestions.Book\x12.\n\x0cvector_clock\x18\x04 \x01(\x0b\x32\x18.suggestions.VectorClock2\x83\x02\n\x12SuggestionsService\x12J\n\tInitOrder\x12\x1d.suggestions.InitOrderRequest\x1a\x1e.suggestions.InitOrderResponse\x12R\n\x13GenerateSuggestions\x12\x19.suggestions.EventRequest\x1a .suggestions.SuggestionsResponse\x12M\n\nClearOrder\x12\x1e.suggestions.ClearOrderRequest\x1a\x1f.suggestions.ClearOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._loaded_options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCK']._serialized_start=34
  _globals['_VECTORCLOCK']._serialized_end=145
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_start=101
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_end=145
  _globals['_INITORDERREQUEST']._serialized_start=147
  _globals['_INITORDERREQUEST']._serialized_end=273
  _globals['_INITORDERRESPONSE']._serialized_start=275
  _globals['_INITORDERRESPONSE']._serialized_end=376
  _globals['_EVENTREQUEST']._serialized_start=378
  _globals['_EVENTREQUEST']._serialized_end=458
  _globals['_CLEARORDERREQUEST']._serialized_start=460
  _globals['_CLEARORDERREQUEST']._serialized_end=551
  _globals['_CLEARORDERRESPONSE']._serialized_start=553
  _globals['_CLEARORDERRESPONSE']._serialized_end=655
  _globals['_BOOK']._serialized_start=657
  _globals['_BOOK']._serialized_end=711
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=714
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=856
  _globals['_SUGGESTIONSSERVICE']._serialized_start=859
  _globals['_SUGGESTIONSSERVICE']._serialized_end=1118
# @@protoc_insertion_point(module_scope)
