# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books_database.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'books_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ooks_database.proto\x12\x0e\x62ooks_database\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"P\n\x0cReadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05stock\x18\x03 \x01(\x05\x12\x0f\n\x07version\x18\x04 \x01(\x03\"U\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x10\n\x08order_id\x18\x04 \x01(\t\"B\n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x03\"o\n\x15ReplicateWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x10\n\x08order_id\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\x03\"K\n\x16ReplicateWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x03\"!\n\x0bPingRequest\x12\x12\n\nreplica_id\x18\x01 \x01(\t\"\\\n\x0cPingResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x12\n\nreplica_id\x18\x02 \x01(\t\x12\x12\n\nis_primary\x18\x03 \x01(\x08\x12\x15\n\rreplica_count\x18\x04 \x01(\x05\x32\xbc\x02\n\rBooksDatabase\x12\x41\n\x04Read\x12\x1b.books_database.ReadRequest\x1a\x1c.books_database.ReadResponse\x12\x44\n\x05Write\x12\x1c.books_database.WriteRequest\x1a\x1d.books_database.WriteResponse\x12_\n\x0eReplicateWrite\x12%.books_database.ReplicateWriteRequest\x1a&.books_database.ReplicateWriteResponse\x12\x41\n\x04Ping\x12\x1b.books_database.PingRequest\x1a\x1c.books_database.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=40
  _globals['_READREQUEST']._serialized_end=68
  _globals['_READRESPONSE']._serialized_start=70
  _globals['_READRESPONSE']._serialized_end=150
  _globals['_WRITEREQUEST']._serialized_start=152
  _globals['_WRITEREQUEST']._serialized_end=237
  _globals['_WRITERESPONSE']._serialized_start=239
  _globals['_WRITERESPONSE']._serialized_end=305
  _globals['_REPLICATEWRITEREQUEST']._serialized_start=307
  _globals['_REPLICATEWRITEREQUEST']._serialized_end=418
  _globals['_REPLICATEWRITERESPONSE']._serialized_start=420
  _globals['_REPLICATEWRITERESPONSE']._serialized_end=495
  _globals['_PINGREQUEST']._serialized_start=497
  _globals['_PINGREQUEST']._serialized_end=530
  _globals['_PINGRESPONSE']._serialized_start=532
  _globals['_PINGRESPONSE']._serialized_end=624
  _globals['_BOOKSDATABASE']._serialized_start=627
  _globals['_BOOKSDATABASE']._serialized_end=943
# @@protoc_insertion_point(module_scope)
