# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/books_database/books_database.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'utils/pb/books_database/books_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/books_database/books_database.proto\x12\x05\x62ooks\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"a\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\x12\x16\n\x0e\x65xpected_stock\x18\x03 \x01(\x05\x12\x17\n\x0fis_replica_sync\x18\x04 \x01(\x08\"1\n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"J\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\x12\x17\n\x0fis_replica_sync\x18\x03 \x01(\x08\"1\n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x17\n\x0fis_replica_sync\x18\x02 \x01(\x08\"2\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x17\n\x0fis_replica_sync\x18\x02 \x01(\x08\"1\n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x99\x02\n\rBooksDatabase\x12/\n\x04Read\x12\x12.books.ReadRequest\x1a\x13.books.ReadResponse\x12\x32\n\x05Write\x12\x13.books.WriteRequest\x1a\x14.books.WriteResponse\x12\x38\n\x07Prepare\x12\x15.books.PrepareRequest\x1a\x16.books.PrepareResponse\x12\x35\n\x06\x43ommit\x12\x14.books.CommitRequest\x1a\x15.books.CommitResponse\x12\x32\n\x05\x41\x62ort\x12\x13.books.AbortRequest\x1a\x14.books.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.books_database.books_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=55
  _globals['_READREQUEST']._serialized_end=83
  _globals['_READRESPONSE']._serialized_start=85
  _globals['_READRESPONSE']._serialized_end=114
  _globals['_WRITEREQUEST']._serialized_start=116
  _globals['_WRITEREQUEST']._serialized_end=213
  _globals['_WRITERESPONSE']._serialized_start=215
  _globals['_WRITERESPONSE']._serialized_end=264
  _globals['_PREPAREREQUEST']._serialized_start=266
  _globals['_PREPAREREQUEST']._serialized_end=340
  _globals['_PREPARERESPONSE']._serialized_start=342
  _globals['_PREPARERESPONSE']._serialized_end=391
  _globals['_COMMITREQUEST']._serialized_start=393
  _globals['_COMMITREQUEST']._serialized_end=451
  _globals['_COMMITRESPONSE']._serialized_start=453
  _globals['_COMMITRESPONSE']._serialized_end=503
  _globals['_ABORTREQUEST']._serialized_start=505
  _globals['_ABORTREQUEST']._serialized_end=562
  _globals['_ABORTRESPONSE']._serialized_start=564
  _globals['_ABORTRESPONSE']._serialized_end=613
  _globals['_BOOKSDATABASE']._serialized_start=616
  _globals['_BOOKSDATABASE']._serialized_end=897
# @@protoc_insertion_point(module_scope)
