# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/order_queue/order_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x12\x0border_queue\"o\n\x0bVectorClock\x12\x32\n\x05\x63lock\x18\x01 \x03(\x0b\x32#.order_queue.VectorClock.ClockEntry\x1a,\n\nClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"o\n\x0bQueuedOrder\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05items\x18\x03 \x03(\t\x12.\n\x0cvector_clock\x18\x04 \x01(\x0b\x32\x18.order_queue.VectorClock\"9\n\x0e\x45nqueueRequest\x12\'\n\x05order\x18\x01 \x01(\x0b\x32\x18.order_queue.QueuedOrder\"3\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"?\n\x11LeadershipRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\x15\n\rlease_seconds\x18\x02 \x01(\x05\"g\n\x12LeadershipResponse\x12\x0f\n\x07granted\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x1c\n\x14lease_expiry_unix_ms\x18\x03 \x01(\x03\x12\x0f\n\x07message\x18\x04 \x01(\t\"U\n\x0e\x44\x65queueRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12.\n\x0cvector_clock\x18\x02 \x01(\x0b\x32\x18.order_queue.VectorClock\"o\n\x0f\x44\x65queueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\thas_order\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\'\n\x05order\x18\x04 \x01(\x0b\x32\x18.order_queue.QueuedOrder2\xf8\x01\n\x11OrderQueueService\x12\x44\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\x12W\n\x14TryAcquireLeadership\x12\x1e.order_queue.LeadershipRequest\x1a\x1f.order_queue.LeadershipResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._loaded_options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCK']._serialized_start=55
  _globals['_VECTORCLOCK']._serialized_end=166
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_start=122
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_end=166
  _globals['_QUEUEDORDER']._serialized_start=168
  _globals['_QUEUEDORDER']._serialized_end=279
  _globals['_ENQUEUEREQUEST']._serialized_start=281
  _globals['_ENQUEUEREQUEST']._serialized_end=338
  _globals['_ENQUEUERESPONSE']._serialized_start=340
  _globals['_ENQUEUERESPONSE']._serialized_end=391
  _globals['_LEADERSHIPREQUEST']._serialized_start=393
  _globals['_LEADERSHIPREQUEST']._serialized_end=456
  _globals['_LEADERSHIPRESPONSE']._serialized_start=458
  _globals['_LEADERSHIPRESPONSE']._serialized_end=561
  _globals['_DEQUEUEREQUEST']._serialized_start=563
  _globals['_DEQUEUEREQUEST']._serialized_end=648
  _globals['_DEQUEUERESPONSE']._serialized_start=650
  _globals['_DEQUEUERESPONSE']._serialized_end=761
  _globals['_ORDERQUEUESERVICE']._serialized_start=764
  _globals['_ORDERQUEUESERVICE']._serialized_end=1012
# @@protoc_insertion_point(module_scope)
