# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/payment/payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'utils/pb/payment/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eutils/pb/payment/payment.proto\x12\x07payment\"2\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"1\n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"2\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"1\n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x18TransactionStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"<\n\x19TransactionStatusResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t2\x9a\x02\n\x0ePaymentService\x12<\n\x07Prepare\x12\x17.payment.PrepareRequest\x1a\x18.payment.PrepareResponse\x12\x39\n\x06\x43ommit\x12\x16.payment.CommitRequest\x1a\x17.payment.CommitResponse\x12\x36\n\x05\x41\x62ort\x12\x15.payment.AbortRequest\x1a\x16.payment.AbortResponse\x12W\n\x0eGetTransaction\x12!.payment.TransactionStatusRequest\x1a\".payment.TransactionStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.payment.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPAREREQUEST']._serialized_start=43
  _globals['_PREPAREREQUEST']._serialized_end=93
  _globals['_PREPARERESPONSE']._serialized_start=95
  _globals['_PREPARERESPONSE']._serialized_end=144
  _globals['_COMMITREQUEST']._serialized_start=146
  _globals['_COMMITREQUEST']._serialized_end=179
  _globals['_COMMITRESPONSE']._serialized_start=181
  _globals['_COMMITRESPONSE']._serialized_end=231
  _globals['_ABORTREQUEST']._serialized_start=233
  _globals['_ABORTREQUEST']._serialized_end=265
  _globals['_ABORTRESPONSE']._serialized_start=267
  _globals['_ABORTRESPONSE']._serialized_end=316
  _globals['_TRANSACTIONSTATUSREQUEST']._serialized_start=318
  _globals['_TRANSACTIONSTATUSREQUEST']._serialized_end=362
  _globals['_TRANSACTIONSTATUSRESPONSE']._serialized_start=364
  _globals['_TRANSACTIONSTATUSRESPONSE']._serialized_end=424
  _globals['_PAYMENTSERVICE']._serialized_start=427
  _globals['_PAYMENTSERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
